name: Deploy to Cloud Run

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/512124407307/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@project-c270d675-13ea-49f6-8dc.iam.gserviceaccount.com

      - name: Build and Push to Docker Hub
        run: |
          docker login -u edendocker467 -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t edendocker467/sovereign-app:${{ github.sha }} .
          docker push edendocker467/sovereign-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: sovereign-app
          region: us-central1
          image: docker.io/edendocker467/sovereign-app:${{ github.sha }}
